version: "3.9"
services:
  api:
    build:
      context: ..
      dockerfile: devops/Dockerfile
    env_file:
      - ./config/.env.stage
    ports:
      - ${PORT_EXTERNAL}:${PORT}      
    depends_on:
      database:
        condition: service_healthy
  database:
    platform: linux/x86_64
    image: mysql
    env_file:
      - ./config/.env.stage
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - ${DATABASE_PORT_EXTERNAL}:${DATABASE_PORT}
    volumes:
      - database_stage:/var/lib/mysql
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysql --host=$DATABASE_HOST --port=$DATABASE_PORT --user=$DATABASE_USERNAME --password=$DATABASE_PASSWORD $DATABASE_NAME -e \"select 1 as healthy\" || exit 1"
        ]
      interval: 20s
      timeout: 10s
      retries: 3
      start_period: 10s
volumes:
  database_stage: {}
