version: "3.9"
services:
  database:
    platform: linux/x86_64
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - ${DATABASE_PORT_EXTERNAL}:${DATABASE_PORT}
    volumes:
      - database_local:/var/lib/mysql
volumes:
  database_local: {}
